### ISSUE TITLE
TypeError: Request with GET/HEAD method cannot have body while running locally

### ISSUE THREAD

**Issue by borsemayur2** [rikilele/kyuko#1]
I tried to run the sample code given in `README.md`. It threw following error after opening localserver in browser:

![image](https://user-images.githubusercontent.com/47341981/124693746-8edef280-defd-11eb-984b-e94ea955a677.png)

**Comment by borsemayur2** [comment]
Versions:
Deno: 1.11.5
OS: Ubuntu (WSL) on Win 10

**Comment by rikilele** [comment]
Hi @borsemayur2 , thanks for reporting the issue!

I would appreciate it if you could answer this question so I can further clarify the situation:

- May I see the contents of the script you ran with `deployctl`?

Here's what I'm suspecting given the information I have so far:

1. Old hello world?

    I've updated the hello world example to a new one. This is because some of the `req` and `res` handling has changed between the very first time I published this repo and the first time I released `v0.1.0`. Can you try this out?

    ```ts
    import { Kyuko } from "https://deno.land/x/kyuko@v0.2.0";

    const app = new Kyuko();

    app.get("/", (req, res) => {
      res.send("Hello World!");
    });

    app.get("/:name", (req, res) => {
      res.send(`Hello ${req.params.name}!`);
    });

    app.listen();
    ```

    I just released [`v0.2.0`](https://github.com/rikilele/kyuko/releases/tag/v0.2.0) so make sure to check that out too!

1. Bad `Request` from callee?

    The error itself reads "`Request with GET/HEAD method cannot have body`", which implies that a faulty `new Request()` was called. Kyuko doesn't instantiate new `Request` objects, so the error is probably being thrown by some other part of the system. It may be a `deployctl` specific problem, or something could be wrong with the callee (http request) itself.

**Comment by borsemayur2** [comment]
>     1. import { Kyuko } from "https://deno.land/x/kyuko@v0.2.0";
>        
>        const app = new Kyuko();
>        
>        app.get("/", (req, res) => {
>          res.send("Hello World!");
>        });
>        
>        app.get("/:name", (req, res) => {
>          res.send(`Hello ${req.params.name}!`);
>        });
>        
>        app.listen();

Here is the script:

```javascript
import { Kyuko } from "https://raw.githubusercontent.com/rikilele/kyuko/main/mod.ts";

const app = new Kyuko();

app.get("/", (req, res) => {
  res.send("Hello World!");
});

app.get("/:name", (req, res) => {
  res.send(`Hello ${req.params.name}!`);
});

app.listen();

```

**Comment by borsemayur2** [comment]
`v0.2.0` throws same error.

**Comment by borsemayur2** [comment]
The issue was with `deployctl` version (`0.1.0`). Able to run the code after upgrade to `0.3.0`. Thanks.
